import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito_Sans } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { Sidebar } from "@/components/layout/sidebar";
import { TopNav } from "@/components/layout/top-nav";

const nunitoSans = Nunito_Sans({ variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={nunitoSans.variable}>
      <body>
        <div className="min-h-screen">
          <TopNav />
          <div className="mx-auto flex max-w-7xl gap-4 px-4 py-4">
            <aside className="hidden w-64 shrink-0 md:block">
              <Sidebar />
            </aside>
            <main className="min-w-0 flex-1 rounded-lg border bg-background p-4">
              <Providers>{children}</Providers>;
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
